services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: