apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: joshua192/flask-app:v3
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: flask-app-config
                  key: WELCOME_MSG
          ports:
            - containerPort: 5000
