apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: joshua192/flask-app:latest
          env:
            - name: WELCOME_MSG
              valueFrom:
                configMapKeyRef:
                  name: flask-app-config
                  key: WELCOME_MSG
            - name: REDIS_HOST
              value: redis  # The hostname of the Redis service
            - name: REDIS_PORT
              value: "6379"  # The port exposed by the Redis service
          ports:
            - containerPort: 5000
